### ISSUE TITLE
Error in setting up nhl db

### ISSUE THREAD

**Issue by pbulsink** [benhowell71/fastRhockey#19]
When trying to setup or update nhl db using the function `update_nhl_db()` the following error occurs:

cannot open URL 'https://raw.githubusercontent.com/saiemgilani/fastRhockey-data/main/nhl/nhl_games_in_data_repo.csv': HTTP status was '404 Not Found'

I can confirm that the file doesn't exist in the target repo.

**Comment by saiemgilani** [comment]
Yeah that's on me. It's a few days from working. But you're doing it right and I will close this issue whenever I get the whole process set up.

**Comment by saiemgilani** [comment]
Done, try it again. closing
